/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CheckboxIndicator: typeof import('radix-vue')['CheckboxIndicator']
    CheckboxRoot: typeof import('radix-vue')['CheckboxRoot']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
    DropdownMenuArrow: typeof import('radix-vue')['DropdownMenuArrow']
    DropdownMenuCheckboxItem: typeof import('radix-vue')['DropdownMenuCheckboxItem']
    DropdownMenuContent: typeof import('radix-vue')['DropdownMenuContent']
    DropdownMenuItem: typeof import('radix-vue')['DropdownMenuItem']
    DropdownMenuItemIndicator: typeof import('radix-vue')['DropdownMenuItemIndicator']
    DropdownMenuLabel: typeof import('radix-vue')['DropdownMenuLabel']
    DropdownMenuPortal: typeof import('radix-vue')['DropdownMenuPortal']
    DropdownMenuRadioGroup: typeof import('radix-vue')['DropdownMenuRadioGroup']
    DropdownMenuRadioItem: typeof import('radix-vue')['DropdownMenuRadioItem']
    DropdownMenuRoot: typeof import('radix-vue')['DropdownMenuRoot']
    DropdownMenuSeparator: typeof import('radix-vue')['DropdownMenuSeparator']
    DropdownMenuSub: typeof import('radix-vue')['DropdownMenuSub']
    DropdownMenuSubContent: typeof import('radix-vue')['DropdownMenuSubContent']
    DropdownMenuSubTrigger: typeof import('radix-vue')['DropdownMenuSubTrigger']
    DropdownMenuTrigger: typeof import('radix-vue')['DropdownMenuTrigger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tree: typeof import('./src/components/Tree.vue')['default']
  }
}
